const mongoose = require("mongoose");

const protocolSchema = new mongoose.Schema({
  date: { type: String, required: true, default: null },
  time: { type: String, required: true, default: null },
  ip_address: { type: String, required: true, default: null },
  ofp_uid: { type: String, required: true, default: null },

  V_R: { type: String, default: null },
  In1_R1: { type: String, default: null },
  In1_RPF: { type: String, default: null },
  V_Y: { type: String, default: null },
  In1_Y1: { type: String, default: null },
  In1_YPF: { type: String, default: null },
  V_B: { type: String, default: null },
  In1_B1: { type: String, default: null },
  In1_BPF: { type: String, default: null },
  P1_R: { type: String, default: null },
  P1_B: { type: String, default: null },
  P1_Y: { type: String, default: null },
  P1: { type: String, default: null },
  Q1_R: { type: String, default: null },
  Q1_B: { type: String, default: null },
  Q1_Y: { type: String, default: null },
  Q1: { type: String, default: null },
  S1_R: { type: String, default: null },
  S1_B: { type: String, default: null },
  S1_Y: { type: String, default: null },
  S1: { type: String, default: null },
  Epimp1: { type: String, default: null },
  Epexp1: { type: String, default: null },
  Eqimp1: { type: String, default: null },
  Eqexp1: { type: String, default: null },

  F1_R: { type: String, default: null },
  PF_R1: { type: String, default: null },
  F1_Y: { type: String, default: null },
  PF_Y1: { type: String, default: null },
  F1_B: { type: String, default: null },
  PF_B1: { type: String, default: null },
  F1_P: { type: String, default: null },
  F1_Q: { type: String, default: null },
  F1_S: { type: String, default: null },
  F1_Epimp: { type: String, default: null },
  F1_Epexp: { type: String, default: null },
  F1_Eqimp: { type: String, default: null },
  F1_Eqexp: { type: String, default: null },

  F2_R: { type: String, default: null },
  PF_R2: { type: String, default: null },
  F2_Y: { type: String, default: null },
  PF_Y2: { type: String, default: null },
  F2_B: { type: String, default: null },
  PF_B2: { type: String, default: null },
  F2_P: { type: String, default: null },
  F2_Q: { type: String, default: null },
  F2_S: { type: String, default: null },
  F2_Epimp: { type: String, default: null },
  F2_Epexp: { type: String, default: null },
  F2_Eqimp: { type: String, default: null },
  F2_Eqexp: { type: String, default: null },

  F3_R: { type: String, default: null },
  PF_R3: { type: String, default: null },
  F3_Y: { type: String, default: null },
  PF_Y3: { type: String, default: null },
  F3_B: { type: String, default: null },
  PF_B3: { type: String, default: null },
  F3_P: { type: String, default: null },
  F3_Q: { type: String, default: null },
  F3_S: { type: String, default: null },
  F3_Epimp: { type: String, default: null },
  F3_Epexp: { type: String, default: null },
  F3_Eqimp: { type: String, default: null },
  F3_Eqexp: { type: String, default: null },

  F4_R: { type: String, default: null },
  PF_R4: { type: String, default: null },
  F4_Y: { type: String, default: null },
  PF_Y4: { type: String, default: null },
  F4_B: { type: String, default: null },
  PF_B4: { type: String, default: null },
  F4_P: { type: String, default: null },
  F4_Q: { type: String, default: null },
  F4_S: { type: String, default: null },
  F4_Epimp: { type: String, default: null },
  F4_Epexp: { type: String, default: null },
  F4_Eqimp: { type: String, default: null },
  F4_Eqexp: { type: String, default: null },

  F5_R: { type: String, default: null },
  PF_R5: { type: String, default: null },
  F5_Y: { type: String, default: null },
  PF_Y5: { type: String, default: null },
  F5_B: { type: String, default: null },
  PF_B5: { type: String, default: null },
  F5_P: { type: String, default: null },
  F5_Q: { type: String, default: null },
  F5_S: { type: String, default: null },
  F5_Epimp: { type: String, default: null },
  F5_Epexp: { type: String, default: null },
  F5_Eqimp: { type: String, default: null },
  F5_Eqexp: { type: String, default: null },

  F6_R: { type: String, default: null },
  PF_R6: { type: String, default: null },
  F6_Y: { type: String, default: null },
  PF_Y6: { type: String, default: null },
  F6_B: { type: String, default: null },
  PF_B6: { type: String, default: null },
  F6_P: { type: String, default: null },
  F6_Q: { type: String, default: null },
  F6_S: { type: String, default: null },
  F6_Epimp: { type: String, default: null },
  F6_Epexp: { type: String, default: null },
  F6_Eqimp: { type: String, default: null },
  F6_Eqexp: { type: String, default: null },

  F7_R: { type: String, default: null },
  PF_R7: { type: String, default: null },
  F7_Y: { type: String, default: null },
  PF_Y7: { type: String, default: null },
  F7_B: { type: String, default: null },
  PF_B7: { type: String, default: null },
  F7_P: { type: String, default: null },
  F7_Q: { type: String, default: null },
  F7_S: { type: String, default: null },
  F7_Epimp: { type: String, default: null },
  F7_Epexp: { type: String, default: null },
  F7_Eqimp: { type: String, default: null },
  F7_Eqexp: { type: String, default: null },

  F8_R: { type: String, default: null },
  PF_R8: { type: String, default: null },
  F8_Y: { type: String, default: null },
  PF_Y8: { type: String, default: null },
  F8_B: { type: String, default: null },
  PF_B8: { type: String, default: null },
  F8_P: { type: String, default: null },
  F8_Q: { type: String, default: null },
  F8_S: { type: String, default: null },
  F8_Epimp: { type: String, default: null },
  F8_Epexp: { type: String, default: null },
  F8_Eqimp: { type: String, default: null },
  F8_Eqexp: { type: String, default: null }
}, {
  timestamps: true,
});



module.exports = mongoose.model("Protocols", protocolSchema);
